In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


print('Hello')
data = pd.read_csv(r'C:\Users\ashionye.aninze\Documents\synthetic-data-rough-note\data\artificial_hes_ae_202302_v1_sample\artificial_hes_ae_0708.csv')

Hello

C:\Users\ashionye.aninze\AppData\Local\Temp\ipykernel_24124\1345189480.py:8: DtypeWarning: Columns (129,141) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r'C:\Users\ashionye.aninze\Documents\synthetic-data-rough-note\data\artificial_hes_ae_202302_v1_sample\artificial_hes_ae_0708.csv')

In [6]:
data.head()

,FYEAR,PARTYEAR,PSEUDO_HESID,AEKEY,AEKEY_FLAG,AEARRIVALMODE,AEATTEND_EXC_PLANNED,AEATTENDCAT,AEATTENDDISP,AEDEPTTYPE,...,LSOA11,MSOA11,PROVDIST,PROVDIST_FLAG,NER_GP_PRACTICE,NER_RESIDENCE,NER_TREATMENT,SITETRET,SITEDIST,SITEDIST_FLAG
0,708,200799,TESTLMgmxx4BW0MY95QVCCDpQc0pOIVW,502918283753,1,2,0,1,3,99,...,E01007065,E02001802,0.26,5.0,NaN,NaN,NaN,NaN,NaN,NaN
1,708,200799,TEST1bkwgyU7co8ESC06q2wOfrxj3UA0,419366440791,1,2,1,2,1,99,...,E01006200,E02004210,3.89,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,708,200799,TEST1bkwgyU7co8ESC06q2wOfrxj3UA0,846671915575,1,2,1,1,3,99,...,E01001320,E02001950,2.56,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,708,200799,TESTQAIuSanLgpC0viam05LCEml702op,479306996883,1,2,1,1,1,99,...,E01011458,E02000453,1.31,5.0,NaN,NaN,NaN,NaN,NaN,NaN
4,708,200799,TEST6FXSKBClkLES7fu5A8U3t5b5mo7l,725682360706,1,2,1,1,2,99,...,E01022644,E02005884,1.58,3.0,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data.describe()

,FYEAR,PARTYEAR,AEKEY,AEKEY_FLAG,AEARRIVALMODE,AEATTEND_EXC_PLANNED,AEATTENDCAT,AEATTENDDISP,AEDEPTTYPE,AEINCLOCTYPE,...,TRETDUR,TRETTIME,PROVDIST,PROVDIST_FLAG,NER_GP_PRACTICE,NER_RESIDENCE,NER_TREATMENT,SITETRET,SITEDIST,SITEDIST_FLAG
count,10000.0,10000.0,1.000000e+04,10000.0,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,8361.000000,8521.00000,0.0,0.0,0.0,0.0,0.0,0.0
mean,708.0,200799.0,5.031052e+11,1.0,1.899800,0.964800,1.133000,3.720400,98.834400,49.583800,...,81.453000,1778.402700,10.932365,3.83746,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,0.0,2.879785e+11,0.0,1.082163,0.184294,0.746704,6.276987,4.013351,37.610121,...,123.576896,1180.112254,22.649437,0.98676,NaN,NaN,NaN,NaN,NaN,NaN
min,708.0,200799.0,9.368645e+07,1.0,1.000000,0.000000,1.000000,1.000000,1.000000,10.000000,...,0.000000,0.000000,0.060000,3.00000,NaN,NaN,NaN,NaN,NaN,NaN
25%,708.0,200799.0,2.566478e+11,1.0,2.000000,1.000000,1.000000,2.000000,99.000000,10.000000,...,20.000000,1043.750000,2.740000,3.00000,NaN,NaN,NaN,NaN,NaN,NaN
50%,708.0,200799.0,5.042284e+11,1.0,2.000000,1.000000,1.000000,3.000000,99.000000,50.000000,...,50.000000,1544.500000,5.130000,3.00000,NaN,NaN,NaN,NaN,NaN,NaN
75%,708.0,200799.0,7.504777e+11,1.0,2.000000,1.000000,1.000000,3.000000,99.000000,91.000000,...,95.000000,2130.000000,11.060000,5.00000,NaN,NaN,NaN,NaN,NaN,NaN
max,708.0,200799.0,9.999187e+11,1.0,9.000000,1.000000,9.000000,99.000000,99.000000,99.000000,...,948.000000,4000.000000,296.310000,5.00000,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
correlation_matrix = data.corr(numeric_only=True)
print(correlation_matrix)

               FYEAR  PARTYEAR     AEKEY  AEKEY_FLAG  AEARRIVALMODE  \
FYEAR            NaN       NaN       NaN         NaN            NaN
PARTYEAR         NaN       NaN       NaN         NaN            NaN
AEKEY            NaN       NaN  1.000000         NaN       0.021612
AEKEY_FLAG       NaN       NaN       NaN         NaN            NaN
AEARRIVALMODE    NaN       NaN  0.021612         NaN       1.000000
...              ...       ...       ...         ...            ...
NER_RESIDENCE    NaN       NaN       NaN         NaN            NaN
NER_TREATMENT    NaN       NaN       NaN         NaN            NaN
SITETRET         NaN       NaN       NaN         NaN            NaN
SITEDIST         NaN       NaN       NaN         NaN            NaN
SITEDIST_FLAG    NaN       NaN       NaN         NaN            NaN

               AEATTEND_EXC_PLANNED  AEATTENDCAT  AEATTENDDISP  AEDEPTTYPE  \
FYEAR                           NaN          NaN           NaN         NaN
PARTYEAR                        NaN          NaN           NaN         NaN
AEKEY                     -0.004460    -0.004061     -0.000966    0.008327
AEKEY_FLAG                      NaN          NaN           NaN         NaN
AEARRIVALMODE             -0.003144    -0.003556     -0.003713   -0.006170
...                             ...          ...           ...         ...
NER_RESIDENCE                   NaN          NaN           NaN         NaN
NER_TREATMENT                   NaN          NaN           NaN         NaN
SITETRET                        NaN          NaN           NaN         NaN
SITEDIST                        NaN          NaN           NaN         NaN
SITEDIST_FLAG                   NaN          NaN           NaN         NaN

               AEINCLOCTYPE  ...   TRETDUR  TRETTIME  PROVDIST  PROVDIST_FLAG  \
FYEAR                   NaN  ...       NaN       NaN       NaN            NaN
PARTYEAR                NaN  ...       NaN       NaN       NaN            NaN
AEKEY             -0.001656  ...  0.022923 -0.001564 -0.003786      -0.006707
AEKEY_FLAG              NaN  ...       NaN       NaN       NaN            NaN
AEARRIVALMODE     -0.003895  ... -0.010552 -0.007698 -0.024377       0.008163
...                     ...  ...       ...       ...       ...            ...
NER_RESIDENCE           NaN  ...       NaN       NaN       NaN            NaN
NER_TREATMENT           NaN  ...       NaN       NaN       NaN            NaN
SITETRET                NaN  ...       NaN       NaN       NaN            NaN
SITEDIST                NaN  ...       NaN       NaN       NaN            NaN
SITEDIST_FLAG           NaN  ...       NaN       NaN       NaN            NaN

               NER_GP_PRACTICE  NER_RESIDENCE  NER_TREATMENT  SITETRET  \
FYEAR                      NaN            NaN            NaN       NaN
PARTYEAR                   NaN            NaN            NaN       NaN
AEKEY                      NaN            NaN            NaN       NaN
AEKEY_FLAG                 NaN            NaN            NaN       NaN
AEARRIVALMODE              NaN            NaN            NaN       NaN
...                        ...            ...            ...       ...
NER_RESIDENCE              NaN            NaN            NaN       NaN
NER_TREATMENT              NaN            NaN            NaN       NaN
SITETRET                   NaN            NaN            NaN       NaN
SITEDIST                   NaN            NaN            NaN       NaN
SITEDIST_FLAG              NaN            NaN            NaN       NaN

               SITEDIST  SITEDIST_FLAG
FYEAR               NaN            NaN
PARTYEAR            NaN            NaN
AEKEY               NaN            NaN
AEKEY_FLAG          NaN            NaN
AEARRIVALMODE       NaN            NaN
...                 ...            ...
NER_RESIDENCE       NaN            NaN
NER_TREATMENT       NaN            NaN
SITETRET            NaN            NaN
SITEDIST            NaN            NaN
SITEDIST_FLAG       NaN            NaN

[126 rows x 126 columns]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 165 entries, FYEAR to SITEDIST_FLAG
dtypes: float64(102), int64(24), object(39)
memory usage: 12.6+ MB